spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  profiles:
    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  security:
#    user:
#      password: ${CONFIG_PASS:dev}

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"


server:
  port: ${PORT:8888}
